package fr.pirids.idsapp.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6E4EA1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFECDCFF)
val md_theme_light_onPrimaryContainer = Color(0xFF270057)
val md_theme_light_secondary = Color(0xFF5854A8)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE3DFFF)
val md_theme_light_onSecondaryContainer = Color(0xFF120463)
val md_theme_light_tertiary = Color(0xFF405AA9)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDCE1FF)
val md_theme_light_onTertiaryContainer = Color(0xFF00164D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF2B0052)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF2B0052)
val md_theme_light_surfaceVariant = Color(0xFFE8E0EB)
val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val md_theme_light_outline = Color(0xFF7B757F)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF303030)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0EF)
val md_theme_light_inversePrimary = Color(0xFFAACEC1)

val md_theme_dark_primary = Color(0xFFD6BAFF)
val md_theme_dark_onPrimary = Color(0xFF3E1C6F)
val md_theme_dark_primaryContainer = Color(0xFF553587)
val md_theme_dark_onPrimaryContainer = Color(0xFFECDCFF)
val md_theme_dark_secondary = Color(0xFFC4C0FF)
val md_theme_dark_onSecondary = Color(0xFF292377)
val md_theme_dark_secondaryContainer = Color(0xFF403C8F)
val md_theme_dark_onSecondaryContainer = Color(0xFFE3DFFF)
val md_theme_dark_tertiary = Color(0xFFB5C4FF)
val md_theme_dark_onTertiary = Color(0xFF042978)
val md_theme_dark_tertiaryContainer = Color(0xFF264190)
val md_theme_dark_onTertiaryContainer = Color(0xDCE1FFC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF2B0052)
val md_theme_dark_onBackground = Color(0xFFEFDBFF)
val md_theme_dark_surface = Color(0xFF2B0052)
val md_theme_dark_onSurface = Color(0xFFEFDBFF)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCBC4CF)
val md_theme_dark_outline = Color(0xFF958E99)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE4E2E1)
val md_theme_dark_inverseOnSurface = Color(0xFF303030)
val md_theme_dark_inversePrimary = Color(0xFF44655B)


val seed = Color(0xFF00231B)

val custom_dark_success = Color(0xFF48D5A2)
val custom_dark_onSuccess = Color(0xFFFFFFFF)
val custom_light_success = Color(0xFFAACEC1)
val custom_light_onSuccess = Color(0xFFFFFFFF)
