package fr.pirids.idsapp.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFf2f3f5)
val md_theme_light_onPrimary = Color(0xFF2E2E2E)
val md_theme_light_primaryContainer = Color(0xFF73451f)
val md_theme_light_onPrimaryContainer = Color(0xFFfffcdd)
val md_theme_light_secondary = Color(0xFFd1d5d9)
val md_theme_light_onSecondary = Color(0xFF060607)
val md_theme_light_secondaryContainer = Color(0xFFB9B9B9)
val md_theme_light_onSecondaryContainer = Color(0xFF1E192B)
val md_theme_light_tertiary = Color(0xFF4f5660)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC2C2C2)
val md_theme_light_onTertiaryContainer = Color(0xFF31101D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFffffff)
val md_theme_light_onBackground = Color(0xFF1F1F1F)
val md_theme_light_surface = Color(0xFFF0F0F0)
val md_theme_light_onSurface = Color(0xFF242424)
val md_theme_light_surfaceVariant = Color(0xFFEEEEEE)
val md_theme_light_onSurfaceVariant = Color(0xFFC7C7C7)
val md_theme_light_outline = Color(0xFFC4C4C4)
val md_theme_light_inverseOnSurface = Color(0xFFB8B8B8)
val md_theme_light_inverseSurface = Color(0xFF414141)
val md_theme_light_inversePrimary = Color(0xFF353535)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF979797)
val md_theme_light_surfaceTintColor = Color(0xFF808080)

val md_theme_dark_primary = Color(0xFF121212)
val md_theme_dark_onPrimary = Color(0xFFf5f5f5)
val md_theme_dark_primaryContainer = Color(0xFF73451f)
val md_theme_dark_onPrimaryContainer = Color(0xFFfffcdd)
val md_theme_dark_secondary = Color(0xFFB6B6B6)
val md_theme_dark_onSecondary = Color(0xFF1D1D1D)
val md_theme_dark_secondaryContainer = Color(0xFF313131)
val md_theme_dark_onSecondaryContainer = Color(0xFFf5f5f5)
val md_theme_dark_tertiary = Color(0xFF4E4A45)
val md_theme_dark_onTertiary = Color(0xFFf5f5f5)
val md_theme_dark_tertiaryContainer = Color(0xFFB9B9B9)
val md_theme_dark_onTertiaryContainer = Color(0xFF3A3A3A)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF2E2E2E)
val md_theme_dark_onBackground = Color(0xFFf5f5f5)
val md_theme_dark_surface = Color(0xFF2a2a2a)
val md_theme_dark_onSurface = Color(0xFFfffcdd)
val md_theme_dark_surfaceVariant = Color(0xFF4E4A45)
val md_theme_dark_onSurfaceVariant = Color(0xFFf5f5f5)
val md_theme_dark_outline = Color(0xFF99948F)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1E)
val md_theme_dark_inverseSurface = Color(0xFFf5f5f5)
val md_theme_dark_inversePrimary = Color(0xFFBBBBBB)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFf5f5f5)
val md_theme_dark_surfaceTintColor = Color(0xFFf5f5f5)


val seed = Color(0xFF777777)

val custom_light_success = Color(0xFFAACEC1)
val custom_light_onSuccess = Color(0xFFFFFFFF)

val custom_dark_success = Color(0xFF48D5A2)
val custom_dark_onSuccess = Color(0xFFFFFFFF)
