name: Build Application

on:
  release:
    types: [released, prereleased]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Set up keystore file
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > idsapp-release-key.jks

      - name: Set up keystore properties
        run: echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 --decode > keystore.properties

      - name: Build Dokka with Gradle
        run: ./gradlew dokkaHtml

      - name: Zip Dokka
        run: cd app/build/dokka && zip -r documentation.zip html

      - name: Upload Dokka
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/dokka/documentation.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release APK with Gradle
        run: ./gradlew assembleRelease

      - name: Rename release APK
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/IDS-App.apk

      - name: Build Release AAB with Gradle
        run: ./gradlew bundleRelease

      - name: Rename release AAB
        run: mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/IDS-App.aab

      - name: Upload Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/IDS-App.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release AAB
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/bundle/release/IDS-App.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


#      - if: failure()
#        name: Delete release
#        run: |
#          curl -s -X DELETE \
#            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            https://api.github.com/repos/${{ github.event.repository.full_name }}/releases/${{ github.event.release.id }}
#          curl -s -X DELETE \
#            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            https://api.github.com/repos/${{ github.event.repository.full_name }}/git/refs/tags/${{ github.event.release.tag_name }}