name: Test with JUnit

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Tests with Gradle
        run: ./gradlew test

      # Not yet implemented (will have to use an emulator in CI)
      #- name: Instrumented tests with Gradle
      #  run: ./gradlew connectedAndroidTest